### ISSUE TITLE
YubiKey with WSL2 article

### ISSUE THREAD

**Issue by hirnschmalz** [1-bit-wonder/blog#3]
Since I didn't find any other way to contact you I misuse the Issues of your blog. I want to use my YubiKey within WSL2 and came across your post. Sounds interesting. With your solution (passing the USB device into WSL2) the YubiKey is no longer available on Windows itself - is that true?

If so, this is a showstopper for me, since I also use my YubiKey to GPG sign my emails - which happens on Windows.

**Comment by 1-bit-wonder** [comment]
Hi @hirnschmalz, I trust you've found an answer to this question by now, but yes technically this is the case. However the solution is as simple as disconnecting the key from WSL whenever you need to use it on the Windows host.
